rename Display -> ShowPrimitive because of error in Linux:
sdl_d3d9_triangle.cpp:218:3: error: invalid use of incomplete type 'Display' (aka '_XDisplay')
                Display();
                ^~~~~~~~~